branches:
    except:
      - 1.0.13_OSX
      - /[0-9].+[0-9]_MSVC+[0-9]*/
      - /[0-9].+[0-9]_OSX/
      - /^untagged/
version: '{build}'
platform:
  - x64
image: 
  - Visual Studio 2019
environment:
  MKL_LICENSE_FILE:
    secure: A5hBQ7mj5AKj5G/EHyznfyh00Brb92UkZ3MRZMrcSjqGyyVsH+sbg35pJRNEGs/Z
  LICLOCAL:
    secure: 2wEyKqfdkKVnTmihIh+X5g==  
  RTOOLS_ARCH: x86_64

install:
  - ps: Import-Module .\script.ps1
  - ps: SetTimezone
  - ps: Invoke-WebRequest https://ftp.osuosl.org/pub/cran/bin/windows/base/R-4.0.2-win.exe -OutFile Rwin.exe
  - ps: .\Rwin.exe /VERYSILENT
  - ps: ls 'C:\Program Files\'
  - ps: ls 'C:\Program Files (x86)\'
  - dir
build_script:
  - ps: Invoke-WebRequest $env:MKL_LICENSE_FILE -OutFile license.lic
  - mkdir "C:\\Program Files (x86)\\Common Files\\Intel"
  - mkdir "C:\\Program Files (x86)\Common Files\Intel\\Licenses\\"
  - mv license.lic "C:\\Program Files (x86)\\Common Files\\Intel\\Licenses\\"
  - ps: Invoke-WebRequest http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16896/w_mkl_2020.3.279.exe -OutFile mkl.exe
  - mkl.exe --silent -a install --eula=accept --output=install.log --intel_sw_improvement_program_consent=no
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
  - dumpbin /exports Rblas.dll > Rblas_list.txt
  - dumpbin /exports Rlapack.dll > Rlapack_list_R.txt
  - bash -c 'mkdir $APPVEYOR_BUILD_FOLDER/$BUILD_NAME'
  - bash -c 'cp C:/Program Files/R/R-4.0.2/bin/x64/*.txt $APPVEYOR_BUILD_FOLDER/$BUILD_NAME'
  - bash -c '7z a $APPVEYOR_BUILD_FOLDER/$BUILD_NAME.zip $APPVEYOR_BUILD_FOLDER/$BUILD_NAME'

artifacts:
  - path: $APPVEYOR_BUILD_FOLDER/$(BUILD_NAME).zip
deploy:
   provider: GitHub
   auth_token:
      secure: ULbLUjD/4O1vvWimREM8MhhTC6yx7PtfPVF+MYaw4ZtJVbINLjQF0hwGCWh7U/ZC
   artifact: $(BUILD_NAME).zip
   prerelease: true
   force_update: true
   tag: $(APPVEYOR_REPO_TAG_NAME)
   on:
      branch: master
      APPVEYOR_REPO_TAG: true
