branches:
    except:
      - 1.0.13_OSX
      - /[0-9].+[0-9]_MSVC+[0-9]*/
      - /[0-9].+[0-9]_OSX/
      - /^untagged/
version: '{build}'
platform:
  - x64
image: 
  - Visual Studio 2019
environment:
  MKL_LICENSE_FILE:
    secure: A5hBQ7mj5AKj5G/EHyznfyh00Brb92UkZ3MRZMrcSjqGyyVsH+sbg35pJRNEGs/Z
  LICLOCAL:
    secure: 2wEyKqfdkKVnTmihIh+X5g==  
  RTOOLS_ARCH: x86_64
  RDEV:
    secure: A5hBQ7mj5AKj5G/EHyznf5XXbNf7jVVKS4PPQ0wJGKjU50Qcy87HFx9KZx0jF3WM

install:
  - ps: Import-Module .\script.ps1
  - ps: SetTimezone
  - ps: Invoke-WebRequest $env:RDEV -OutFile R-devel.zip
  - bash -c 'unzip -qq R-devel.zip'

build_script:
  - ps: Invoke-WebRequest $env:MKL_LICENSE_FILE -OutFile license.lic
  - mkdir "C:\\Program Files (x86)\\Common Files\\Intel"
  - mkdir "C:\\Program Files (x86)\Common Files\Intel\\Licenses\\"
  - mv license.lic "C:\\Program Files (x86)\\Common Files\\Intel\\Licenses\\"
  - ps: Invoke-WebRequest http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16896/w_mkl_2020.3.279.exe -OutFile mkl.exe
  - mkl.exe --silent -a install --eula=accept --output=install.log --intel_sw_improvement_program_consent=no
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
  - ps: cp -r 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl\tools\builder\' 'C:\projects\laptopr\'
  - bash -c 'cp Rlapack_list.txt ./builder/'
  - bash -c 'cp Rblas_list.txt ./builder/'
  - ps: cp 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\redist\intel64\compiler\libiomp5md.dll' 'C:\projects\laptopr\builder\'
  - cd .\builder\
  - nmake libintel64 MKLROOT="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl" export=Rblas_list.txt name=Rblas 
  - nmake libintel64 MKLROOT="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl" export=Rlapack_list.txt name=Rlapack
  - cd ..
  - dumpbin /dependents ./builder/Rlapack.dll
  - bash -c '7z a R.7z ./builder/'

artifacts:
  - path: R.7z
deploy:
  - provider: GitHub
    auth_token:
      secure: cBYFQ45LcM135O5JkMlE7tb4XmAUK709NnFe0o2RhpMUOFbRzqW6OFY7X2x/U/TZ
    artifact: R.7z
    release: R-v$(APPVEYOR_BUILD_VERSION)
    prerelease: false
    description: R-v$(APPVEYOR_BUILD_VERSION)
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
