# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- powershell: .\step1.ps1
- bash: mkdir "C:\\Program Files (x86)\\Common Files\\Intel"
- bash: mkdir "C:\\Program Files (x86)\\Common Files\Intel\\Licenses\\"
- bash: mv $env:LICLOCAL "C:\Program Files (x86)\Common Files\Intel\Licenses\"
- powershell: .\step2.ps1
- script:  C:\rtools40\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/full-build.sh"
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './R-devel/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: './$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
- task: GithubRelease@0
  displayName: 'Create GitHub Release'
  inputs:
    gitHubConnection: pushbinary
    repositoryName: MitsuhaMiyamizu/SeqMap
    tagSource: manual
    tag: $(Build.BuildNumber)_MKL
    assets: |
      ./$(Build.BuildId).zip
