name: LaptopR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  rsource_url: https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz
  RTOOLS_ARCH: x86_64
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Preparation
        shell: powershell
        run: |
          Import-Module .\script.ps1
          SetTimezone
          InstallInno
          InstallMiktex
          InstallRtoolsExe
          Invoke-WebRequest $env:rsource_url -OutFile R-4.0.3.tar.gz
      - name: Run a Full Build
        run: |
          C:\rtools40\usr\bin\bash --login -c "tar xf /d/a/LaptopR/LaptopR/R-4.0.3.tar.gz"
          C:\rtools40\usr\bin\bash --login -c "/d/a/LaptopR/LaptopR/full-build.sh"
      - name: Run Stage 1
        shell: cmd
        run: |
          mkdir "C:\\Program Files (x86)\\Common Files\\Intel"
          mkdir "C:\\Program Files (x86)\\Common Files\Intel\\Licenses\\"
          Invoke-WebRequest $env:MKL_LICENSE_FILE -OutFile $env:LICLOCAL
      - name: Run Stage 2
        run: |
          mv $env:LICLOCAL "C:\Program Files (x86)\Common Files\Intel\Licenses\"
      - name: Run Stage 3
        shell: powershell
        run: |
          powershell: .\step2.ps1
