name: LaptopR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  rsource_url: https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz
  RTOOLS_ARCH: x86_64
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Stage 1
        shell: powershell
        env:
          mkl_license: ${{ secrets.MKL_LICENSE_FILE }}
        run: |
          Invoke-WebRequest $env:mkl_license -OutFile license.lic
          ls .
      - name: Run Stage 3
        shell: powershell
        run: |
          (new-object Net.WebClient).DownloadFile('http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16896/w_mkl_2020.3.279.exe','mkl.exe')
          ls
      - name: Install MKL
        shell: cmd
        run: |
          mkl.exe --silent -a install --license=.\license.lic --eula=accept --output=install.log --intel_sw_improvement_program_consent=no
      - name: Run Stage 4
        run: |
          cp -r 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl\tools\builder\' 'D:\a\LaptopR\LaptopR\'
          cp Rlapack_list.txt .\builder\
          cp Rblas_list.txt .\builder\
          cp 'C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\redist\intel64\compiler\libiomp5md.dll' 'D:\a\LaptopR\LaptopR\builder\'
      - name: Run Stage 2
        shell: cmd
        run: |
          cd D:\a\LaptopR\LaptopR\builder\
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          nmake libintel64 MKLROOT="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl" export=Rblas_list.txt name=Rblas 
          nmake libintel64 MKLROOT="C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.3.279\windows\mkl" export=Rlapack_list.txt name=Rlapack
          dumpbin /dependents .\builder\Rlapack.dll
      - name: Preparation
        shell: powershell
        run: |
          Import-Module .\script.ps1
          SetTimezone
          InstallInno
          InstallMiktex
          InstallRtoolsExe
          Invoke-WebRequest $env:rsource_url -OutFile R-4.0.3.tar.gz
          C:\rtools40\usr\bin\bash --login -c "/d/a/LaptopR/LaptopR/full-build.sh"
